import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const cairo = Cairo({
  variable: "--cairo--sans",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "الرئيسية - زين التنموية",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="ar">
      <body
        className={` ${cairo.className} antialiased text-4xl dark:bg-blackColor`}>
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  );
}
